version: '3.3'

services:
  hazelcast:
    image: multilogin/hazelcast-docker-swarm
    configs:
      - source: hazelcast.xml
        target: /opt/hazelcast/hazelcast.xml
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 10
        window: 90s

configs:
  hazelcast.xml:
    file: ./hazelcast.xml
